"""create index in message table

Revision ID: bc562f3a8372
Revises: e462531ee6c0
Create Date: 2026-07-16 12:47:17.758288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc562f3a8372'
down_revision: Union[str, Sequence[str], None] = 'e462531ee6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chat_history', 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_history', table_name='messages')
    # ### end Alembic commands ###
